version: 2

updates:
  # Enable version updates for npm dependencies in root
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 10
    reviewers:
      - '@sammons2'
    labels:
      - 'dependencies'
      - 'automated'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'

  # Enable version updates for npm dependencies in CLI package
  - package-ecosystem: 'npm'
    directory: '/packages/cli'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 5
    reviewers:
      - '@sammons2'
    labels:
      - 'dependencies'
      - 'cli'
      - 'automated'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'

  # Enable version updates for npm dependencies in Parser package
  - package-ecosystem: 'npm'
    directory: '/packages/parser'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 5
    reviewers:
      - '@sammons2'
    labels:
      - 'dependencies'
      - 'parser'
      - 'automated'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'

  # Enable version updates for npm dependencies in Formatter package
  - package-ecosystem: 'npm'
    directory: '/packages/formatter'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 5
    reviewers:
      - '@sammons2'
    labels:
      - 'dependencies'
      - 'formatter'
      - 'automated'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'

  # Enable version updates for npm dependencies in Website package
  - package-ecosystem: 'npm'
    directory: '/packages/website'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 5
    reviewers:
      - '@sammons2'
    labels:
      - 'dependencies'
      - 'website'
      - 'automated'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 5
    reviewers:
      - '@sammons2'
    labels:
      - 'github-actions'
      - 'automated'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'
